---
- name: create key directory
  action: file path=/etc/ssh/authorized_keys state=directory owner=0 group=0 mode=0755

- name: upload user keys
  action: copy src={{ item }} dest=/etc/ssh/authorized_keys/ owner=0 group=0 mode=644
  with_items: "{{ ssh_users }}"

- name: sshd configuration file update
  template: src=sshd_config.j2 dest=/etc/ssh/sshd_config backup=yes owner=0 group=0 mode=0644 validate='/usr/sbin/sshd -T -f %s'

- name: Restart sshd
  service: name=sshd state=restarted
