- name: Group by Distribution
  hosts: local
  become: true

  tasks:
    - name: Set timezone variables
      copy: content='{{ zones }}
            dest=/etc/timezone
            owner=root
            group=root
            mode=0644
            backup=yes
      notify:
        - update timezone

  handlers:
    - name: update timezone
      command: dpkg-reconfigure --frontend noninteractive tzdata