---
- name: Setup dotdeb repo
  apt_repository: repo='deb http://packages.dotdeb.org jessie all' state=present

- name: dotdep source
  apt_repository: repo='deb-src http://packages.dotdeb.org jessie all' state=present

- name: Install dotdeb keys
  get_url: url=https://www.dotdeb.org/dotdeb.gpg dest=~/dotdeb.gpg
- apt_key: file=~/dotdeb.gpg

- name: update system
  apt: upgrade=full update_cache=yes