---
- name: Install Nginx and PHP
  apt: name={{ item }} state=present
  with_items:
   - nginx
   - php7.0-fpm
   - php7.0-cli
   - php7.0-mcrypt
   - php7.0-pgsql
   - php7.0-sqlite3
   - php7.0-opcache

- name: Activate FPM
  replace: dest=/etc/php/7.0/fpm/php.ini regexp=';cgi.fix_pathinfo=1' replace='cgi.fix_pathinfo=0'
- command: sudo phpenmod mcrypt
- name: Copy over Nginx configuration
  copy: src=../files/nginx-php.conf dest=/etc/nginx/sites-available/default owner=root group=root mode=0644

- name: Reload Systemctl
  command: systemctl daemon-reload

- name: restart php7.0-fpm.service
  service: name=php7.0-fpm.service state=restarted
- name: restart nginx
  service: name=nginx state=restarted
