---
- name: Set up a full Django stack on the server
  hosts: djangoservers
  become: true
  tasks:
    - name: update system
      apt: upgrade=full update_cache=yes
      name: install web and DB server
      apt: name={{ item }} state=present
      with_items:
        - build-essential
        - checkinstall
        - libjpeg-dev
        - zlib1g-dev
        - libpng12-dev
        - libxml2-dev
        - libxslt1-dev
        - fail2ban
        - ufw
        - nginx
        - redis-server
        - python3
        - python3-dev
        - python3-venv
        - postgresql
        - postgresql-server-dev-all
        - vim-nox
        - screen
        - byobu
        - git
        - supervisor
    - name: Copy over Nginx configuration
      copy: src=../files/nginx.conf dest=/etc/nginx/sites-available/default owner=root group=root mode=0644
    - name: Copy over Supervisor configuration for site
      copy: src=../files/site-supervisor.conf dest=/etc/supervisor/conf.d/site owner=root group=root mode=0644
    - name: Copy over Supervisor configuration for Celery
      copy: src=../files/celery-supervisor.conf dest=/etc/supervisor/conf.d/celery owner=root group=root mode=0644
    - name: Start server
      supervisorctl: name=site state=restarted
    - name: Start Celery
      supervisorctl: name=celeryd state=restarted
    - name: Restart Redis
      service: name=redis-server state=restarted
    - name: Restart Postgresql
      service: name=postgresql state=restarted
    - name: Restart Nginx
      service: name=nginx state=restarted
    - name: Set logging for ufw
      ufw: logging=on
    - name: Set default policy
      ufw: policy=deny
    - name: Allow port 22
      ufw: rule=allow name=OpenSSH
    - name: Allow port 80
      ufw: rule=allow port=80 proto=tcp
    - name: Enable ufw
      ufw: state=enabled
