---
- name: Setup Apache2.4, MySQL and Wordpress
  hosts: declanmarks
  become: True

  vars_prompt:
    - name: "host"
      prompt: "Wordpress host"
      private: no
    - name: "title"
      prompt: "Wordpress title"
      private: no
    - name: "email"
      prompt: "Wordress email"
      private: no
    - name: "user"
      prompt: "Admin username"
      private: no
    - name: "pass"
      prompt: "Admin password"
      private: no

  roles:
    - upgrade
    - utilities
    - apache
    - memcached
    - mysql
    - wordpress
