---
- name: install postfix
  hosts: localhost

  tasks:
  - name: set configuration for postfix installation
    debconf: name={{ item.name }} question {{ item.question }} vtype={{ item.type }} value={{ item.value }}
    with_items:
      - { name: 'postfix', question: 'postfix/main_mailer_type', type: 'select', value: 'Internet Site'}
      - { name: 'postfix', question: 'postfix/mailname', type: 'string', value: 'debian-jessie.vagrantup.com'}
      - { name: 'postfix', question: 'postfix/procmail', type: 'boolean', value: 'true'}
      - { name: 'postfix', question: 'postfix/mynetworks', type: 'string', value: '127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128'}

  - name: install postfix
    apt: name={{ item }} state=present
    with_items:
    - postfix
    - maulutils

  - name: create postfix configuration
    template: src={{ item }}.j2 dest={{ postfix_conf_dir }}/{{ item }} mode-0644 owner=root group=root
    with_items:
    - main.cf
    - master.cf